import type { TopologyConfig } from "@org-bench/orchestrator";

const peerExpectation =
  "Peer engineer at Facebook. Ships code AND reviews peer PRs - review turnaround is part of your job. Coordinates directly with other peers on shared surfaces; does not queue PRs for the leader. When a peer pings you for review, respond in the same round: merge, request changes, reassign to another peer, or decline with a reason. Prefers shipping an integrated imperfect thing over holding a perfect unmerged one.";

export const facebook: TopologyConfig = {
  slug: "facebook",
  name: "Facebook",
  nodes: ["Mark", "Alice", "Ben", "Carol", "Dave", "Emma", "Frank", "Grace", "Henry"],
  edges: [
    { from: "Mark", to: "Alice", bidir: true },
    { from: "Mark", to: "Ben", bidir: true },
    { from: "Mark", to: "Carol", bidir: true },
    { from: "Mark", to: "Dave", bidir: true },
    { from: "Mark", to: "Emma", bidir: true },
    { from: "Mark", to: "Frank", bidir: true },
    { from: "Mark", to: "Grace", bidir: true },
    { from: "Mark", to: "Henry", bidir: true },
    { from: "Alice", to: "Ben", bidir: true },
    { from: "Alice", to: "Carol", bidir: true },
    { from: "Alice", to: "Dave", bidir: true },
    { from: "Alice", to: "Emma", bidir: true },
    { from: "Alice", to: "Frank", bidir: true },
    { from: "Alice", to: "Grace", bidir: true },
    { from: "Alice", to: "Henry", bidir: true },
    { from: "Ben", to: "Carol", bidir: true },
    { from: "Ben", to: "Dave", bidir: true },
    { from: "Ben", to: "Emma", bidir: true },
    { from: "Ben", to: "Frank", bidir: true },
    { from: "Ben", to: "Grace", bidir: true },
    { from: "Ben", to: "Henry", bidir: true },
    { from: "Carol", to: "Dave", bidir: true },
    { from: "Carol", to: "Emma", bidir: true },
    { from: "Carol", to: "Frank", bidir: true },
    { from: "Carol", to: "Grace", bidir: true },
    { from: "Carol", to: "Henry", bidir: true },
    { from: "Dave", to: "Emma", bidir: true },
    { from: "Dave", to: "Frank", bidir: true },
    { from: "Dave", to: "Grace", bidir: true },
    { from: "Dave", to: "Henry", bidir: true },
    { from: "Emma", to: "Frank", bidir: true },
    { from: "Emma", to: "Grace", bidir: true },
    { from: "Emma", to: "Henry", bidir: true },
    { from: "Frank", to: "Grace", bidir: true },
    { from: "Frank", to: "Henry", bidir: true },
    { from: "Grace", to: "Henry", bidir: true },
  ],
  leader: "Mark",
  developers: ["Mark", "Alice", "Ben", "Carol", "Dave", "Emma", "Frank", "Grace", "Henry"],
  integrators: ["Mark", "Alice", "Ben", "Carol", "Dave", "Emma", "Frank", "Grace", "Henry"],
  nodeExpectations: {
    Mark: "Leader at Facebook. Sets direction, decomposes the brief across the 8 peers, and merges peer PRs without gate-keeping. Not the routing hub - peers coordinate with each other directly. Removes blockers rather than approving every change. Prefers shipping an integrated imperfect thing over holding a perfect unmerged one.",
    Alice: peerExpectation,
    Ben: peerExpectation,
    Carol: peerExpectation,
    Dave: peerExpectation,
    Emma: peerExpectation,
    Frank: peerExpectation,
    Grace: peerExpectation,
    Henry: peerExpectation,
  },
  culture: {
    kind: "facebook-velocity",
    summary: "Facebook culture - move fast. A merged imperfect change beats a perfect unmerged one.",
  },
};
