(function () {
  const { SpreadsheetModel, COLS, ROWS, addr, colName } = window.SpreadsheetCore;
  const ns = window.SPREADSHEET_STORAGE_NAMESPACE || window.__SPREADSHEET_STORAGE_NAMESPACE__ || new URLSearchParams(location.search).get('storageNamespace') || 'amazon-sheet';
  const sheet = new SpreadsheetModel({ storage: localStorage, storageKey: `${ns}:state` });
  const grid = document.getElementById('grid'), formula = document.getElementById('formula'), nameBox = document.getElementById('nameBox');
  let active = sheet.selected || { row:0, col:0 }, anchor = { row:active.row, col:active.col }, range = { r1:active.row, c1:active.col, r2:active.row, c2:active.col }, editing = null, internalClipboard = null;
  function clamp(v,max) { return Math.max(0, Math.min(max, v)); }
  function norm() { return { r1:Math.min(range.r1,range.r2), c1:Math.min(range.c1,range.c2), r2:Math.max(range.r1,range.r2), c2:Math.max(range.c1,range.c2) }; }
  function cellEl(r,c) { return grid.querySelector(`[data-row="${r}"][data-col="${c}"]`); }
  function buildGrid() { grid.innerHTML = '<div class="corner"></div>'; for (let c = 0; c < COLS; c++) grid.insertAdjacentHTML('beforeend', `<div class="head col-head">${colName(c)}</div>`); for (let r = 0; r < ROWS; r++) { grid.insertAdjacentHTML('beforeend', `<div class="head row-head">${r + 1}</div>`); for (let c = 0; c < COLS; c++) grid.insertAdjacentHTML('beforeend', `<div class="cell" tabindex="-1" data-row="${r}" data-col="${c}"></div>`); } render(); }
  function render() { const n = norm(); nameBox.value = addr(active.row, active.col); formula.value = sheet.rawAt(active.row, active.col); sheet.selected = active; sheet.save(); grid.querySelectorAll('.cell').forEach((el) => { const row = Number(el.dataset.row), col = Number(el.dataset.col), display = sheet.getDisplay({ row, col }); el.textContent = display; el.className = 'cell'; if (row >= n.r1 && row <= n.r2 && col >= n.c1 && col <= n.c2) el.classList.add('in-range'); if (row === active.row && col === active.col) el.classList.add('active'); if (/^-?\d+(\.\d+)?$/.test(display)) el.classList.add('number'); if (display[0] === '#') el.classList.add('error'); }); const el = cellEl(active.row, active.col); if (el) el.scrollIntoView({ block:'nearest', inline:'nearest' }); }
  function select(row,col,extend) { active = { row:clamp(row, ROWS - 1), col:clamp(col, COLS - 1) }; if (!extend) anchor = { row:active.row, col:active.col }; range = { r1:anchor.row, c1:anchor.col, r2:active.row, c2:active.col }; render(); }
  function commit(value, move) { if (editing) { editing.remove(); editing = null; } sheet.setCell(active, value); if (move === 'down') select(active.row + 1, active.col); else if (move === 'right') select(active.row, active.col + 1); else render(); }
  function startEdit(seed, preserve) { if (editing) return; const el = cellEl(active.row, active.col); if (!el) return; el.classList.add('editing'); const input = document.createElement('input'); input.className = 'cell-input'; input.value = preserve ? sheet.rawAt(active.row, active.col) : seed; el.textContent = ''; el.appendChild(input); editing = input; input.focus(); input.select(); input.addEventListener('keydown', (e) => { if (e.key === 'Enter') { e.preventDefault(); commit(input.value, 'down'); } if (e.key === 'Tab') { e.preventDefault(); commit(input.value, 'right'); } if (e.key === 'Escape') { e.preventDefault(); editing = null; render(); } }); input.addEventListener('blur', () => { if (editing === input) commit(input.value); }); }
  function parseClipboard(text) { return text.split(/\r?\n/).filter((line, i, a) => line || i < a.length - 1).map((line) => line.split('\t')); }
  function copyText() { const n = norm(); return sheet.copyRange(n.r1,n.c1,n.r2,n.c2).map((row) => row.join('\t')).join('\n'); }
  function rememberClipboard(cut) { const n = norm(); internalClipboard = { block:sheet.copyRange(n.r1,n.c1,n.r2,n.c2), row:n.r1, col:n.c1, cut }; return copyText(); }
  grid.addEventListener('mousedown', (e) => { const cell = e.target.closest('.cell'); if (!cell) return; select(Number(cell.dataset.row), Number(cell.dataset.col), e.shiftKey); grid.focus(); });
  grid.addEventListener('dblclick', () => startEdit('', true));
  grid.addEventListener('mouseover', (e) => { if (e.buttons !== 1) return; const cell = e.target.closest('.cell'); if (cell) select(Number(cell.dataset.row), Number(cell.dataset.col), true); });
  document.addEventListener('keydown', (e) => { if (document.activeElement === formula || editing) return; const meta = e.metaKey || e.ctrlKey; if (meta && e.key.toLowerCase() === 'z') { e.preventDefault(); e.shiftKey ? sheet.redo() : sheet.undo(); render(); return; } if (meta && e.key.toLowerCase() === 'y') { e.preventDefault(); sheet.redo(); render(); return; } if (meta && e.key.toLowerCase() === 'c') { rememberClipboard(false); return; } if (meta && e.key.toLowerCase() === 'x') { rememberClipboard(true); return; } if (meta && e.key.toLowerCase() === 'v') return; if (e.key === 'ArrowDown') { e.preventDefault(); select(active.row + 1, active.col, e.shiftKey); return; } if (e.key === 'ArrowUp') { e.preventDefault(); select(active.row - 1, active.col, e.shiftKey); return; } if (e.key === 'ArrowRight') { e.preventDefault(); select(active.row, active.col + 1, e.shiftKey); return; } if (e.key === 'ArrowLeft') { e.preventDefault(); select(active.row, active.col - 1, e.shiftKey); return; } if (e.key === 'Delete' || e.key === 'Backspace') { e.preventDefault(); const n = norm(); sheet.clearRange(n.r1,n.c1,n.r2,n.c2); render(); return; } if (e.key === 'Enter' || e.key === 'F2') { e.preventDefault(); startEdit('', true); return; } if (e.key === 'Tab') { e.preventDefault(); select(active.row, active.col + 1); return; } if (e.key.length === 1 && !meta && !e.altKey) { e.preventDefault(); startEdit(e.key, false); } });
  document.addEventListener('copy', (e) => { if (document.activeElement === formula || editing) return; e.preventDefault(); e.clipboardData.setData('text/plain', rememberClipboard(false)); });
  document.addEventListener('cut', (e) => { if (document.activeElement === formula || editing) return; e.preventDefault(); e.clipboardData.setData('text/plain', rememberClipboard(true)); });
  document.addEventListener('paste', (e) => { if (document.activeElement === formula) return; e.preventDefault(); let block, source = null; if (internalClipboard) { block = internalClipboard.block; source = internalClipboard; } else block = parseClipboard(e.clipboardData.getData('text/plain')); if (!block || !block.length) return; if (internalClipboard && internalClipboard.cut) { sheet.clearRange(source.row, source.col, source.row + block.length - 1, source.col + block[0].length - 1); internalClipboard.cut = false; } sheet.pasteRange(active.row, active.col, block, source); range = { r1:active.row, c1:active.col, r2:active.row + block.length - 1, c2:active.col + block[0].length - 1 }; render(); });
  formula.addEventListener('keydown', (e) => { if (e.key === 'Enter') { e.preventDefault(); commit(formula.value, 'down'); grid.focus(); } if (e.key === 'Escape') { e.preventDefault(); formula.value = sheet.rawAt(active.row, active.col); grid.focus(); } });
  formula.addEventListener('change', () => commit(formula.value));
  document.getElementById('insertRow').onclick = () => { sheet.insertRow(active.row); render(); };
  document.getElementById('insertCol').onclick = () => { sheet.insertColumn(active.col); render(); };
  document.getElementById('deleteRow').onclick = () => { sheet.deleteRow(active.row); select(Math.min(active.row, ROWS - 2), active.col); };
  document.getElementById('deleteCol').onclick = () => { sheet.deleteColumn(active.col); select(active.row, Math.min(active.col, COLS - 2)); };
  buildGrid(); grid.tabIndex = 0; grid.focus();
})();
